export const genres: string[] = [
  'Action',
  'Adventure',
  'Animation',
  'Biography',
  'Comedy',
  'Crime',
  'Documentary',
  'Drama',
  'Family',
  'Fantasy',
  'Film-Noir',
  'History',
  'Horror',
  'Music',
  'Musical',
  'Mystery',
  'Romance',
  'Sci-Fi (Science Fiction)',
  'Sport',
  'Superhero',
  'Thriller',
  'War',
  'Western',
  'Crime Thriller',
  'Romantic Comedy',
  'Action Comedy',
  'Supernatural',
  'Psychological Thriller',
  'Historical Drama',
  'Animated Fantasy',
  'Teen Drama',
  'Crime Drama',
  'Science Fiction Horror',
  'Satire',
  'Disaster',
  'Martial Arts',
  'Spy',
  'Epic',
  'Zombie',
  'Slasher',
  'Found Footage',
  'Mockumentary',
  'Coming-of-Age',
  'Courtroom Drama',
  'Gothic',
  'Political Drama',
  'Steampunk',
  'Post-Apocalyptic',
  'Cyberpunk',
  'Silent Film',
];
